"""Criando tabela produto_cadastro

Revision ID: 4c2e10cdf102
Revises: 
Create Date: 2025-11-25 15:34:52.944030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2e10cdf102'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_cadastro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campo_selecao', sa.String(length=50), nullable=False),
    sa.Column('cor_tinta', sa.String(length=50), nullable=True),
    sa.Column('textura_tinta', sa.String(length=50), nullable=True),
    sa.Column('tipo_madeira', sa.String(length=50), nullable=True),
    sa.Column('campo_numero', sa.Integer(), nullable=False),
    sa.Column('campo_selecao_medida', sa.String(length=20), nullable=False),
    sa.Column('tipo_aplicacao', sa.String(length=50), nullable=False),
    sa.Column('Campo_validade', sa.Date(), nullable=False),
    sa.Column('Campo_data_entrada', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('livros')
    op.drop_table('vendas_joao')
    op.drop_table('vendas')
    op.drop_table('produtos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('titulo', sa.TEXT(), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('estoque', sa.INTEGER(), nullable=True),
    sa.Column('estoque_min', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('data_venda', sa.TEXT(), nullable=True),
    sa.Column('pago', sa.TEXT(), nullable=True),
    sa.Column('valor_venda', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas_joao',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('data_compra', sa.TEXT(), nullable=True),
    sa.Column('nome_cliente', sa.TEXT(length=100), nullable=True),
    sa.Column('data_pagamento', sa.TEXT(), nullable=True),
    sa.Column('valor_devido', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('titulo', sa.TEXT(), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('autores', sa.TEXT(), nullable=True),
    sa.Column('estoque', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('produto_cadastro')
    # ### end Alembic commands ###
